### ISSUE TITLE
Error while running InvoiceDemo1 with Polyjuice flag disabled

### ISSUE THREAD

**Issue by warpech** [Starcounter/InvoiceDemo#20]
The following error shows up when trying InvoiceDemo1 in Starcounter edition.

```
[13:09:08, Critical, Starcounter (invoicedemo1db)]
[13:09:08][Step 1/2] Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. System.InvalidOperationException: Polyjuice is not initialized!
[13:09:08][Step 1/2]    at PolyjuiceNamespace.Polyjuice.Map(String appProcessedUri, String mapProcessedUri, Func`2 converterTo, Func`2 converterFrom, String method) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.9854.2\Level1\src\Starcounter\Apps\PolyJuice.cs:line 345
[13:09:08][Step 1/2]    at PolyjuiceNamespace.Polyjuice.Map(String appProcessedUri, String mapProcessedUri, String method) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.9854.2\Level1\src\Starcounter\Apps\PolyJuice.cs:line 212
[13:09:08][Step 1/2]    at Program.Main() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.9854.2\InvoiceDemo\src\InvoiceDemo1\Program.cs:line 22
[13:09:08][Step 1/2] Version: 2.0.9854.2.
[13:09:08][Step 1/2] Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259.
[13:09:08][Step 1/2]    at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.9854.2\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 453
[13:09:08][Step 1/2]    at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.9854.2\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 207
[13:09:08][Step 1/2]    at Starcounter.Hosting.Package.Process() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.9854.2\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 132
[13:09:08][Step 1/2]    at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.9854.2\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 70
[13:09:08][Step 1/2] ErrorCode=4259
[13:09:08][Step 1/2] HResult=-2146233088
[13:09:08][Step 1/2] HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
[13:09:08][Step 1/2] ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[13:09:08][Step 1/2]    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
[13:09:08][Step 1/2]    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
[13:09:08][Step 1/2]    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[13:09:08][Step 1/2]    at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.9854.2\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 437
[13:09:08][Step 1/2] HResult=-2146232828
[13:09:08][Step 1/2] ---> System.InvalidOperationException: Polyjuice is not initialized!
[13:09:08][Step 1/2]    at PolyjuiceNamespace.Polyjuice.Map(String appProcessedUri, String mapProcessedUri, Func`2 converterTo, Func`2 converterFrom, String method) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.9854.2\Level1\src\Starcounter\Apps\PolyJuice.cs:line 345
[13:09:08][Step 1/2]    at PolyjuiceNamespace.Polyjuice.Map(String appProcessedUri, String mapProcessedUri, String method) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.9854.2\Level1\src\Starcounter\Apps\PolyJuice.cs:line 212
[13:09:08][Step 1/2]    at Program.Main() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.9854.2\InvoiceDemo\src\InvoiceDemo1\Program.cs:line 22
[13:09:08][Step 1/2] HResult=-2146233079
```

The error comes from [line](https://github.com/Starcounter/InvoiceDemo/blob/1742999c496bf186ae1795c095e7166db3c41b07/src/InvoiceDemo1/Program.cs#L22):

```c#
PolyjuiceNamespace.Polyjuice.Map("/invoicedemo", "/");
```

@alemoi is there any reason why URL mapping should not be allowed with Polyjuice flag disabled? Perhaps even ontology mapping should be allowed with Polyjuice flag disabled.

**Comment by alemoi** [comment]
Thanks for reporting! I think that should be allowed. Initially it was developed to be a pure Polyjuice functionality (that's why the name is like that, and it enforces `/polyjuice` prefix). But now turns out to be generic. Maybe it should be called `Handle.Map` then. Regarding ontology mapping we can discuss because right now it requires Polyjuice edition. Is this functionality urgent?

**Comment by warpech** [comment]
@alemoi, on Hangouts you proposed to use the following code instead:

```c#
        Handle.GET("/", () => {
            return Self.GET("/invoicedemo");
        });
```

but that code has an opposite problem - it doesn't run with Polyjuice flag **off**.

The solution that starts correctly with the flag on and off:

```c#
        if (Starcounter.Internal.StarcounterEnvironment.PolyjuiceAppsFlag) {
            PolyjuiceNamespace.Polyjuice.Map("/invoicedemo", "/");
        } else {
            Handle.GET("/", () => {
                return Self.GET("/invoicedemo");
            });
        }
```

but even this one shows an error with Polyjuice flag **off**:

> Error 404: File /invoicepage.html. not found

I am running out of ideas... Can you help?

**Comment by alemoi** [comment]
Thanks for reporting! I will get the demo and try to reproduce the issue with the code above!

**Comment by alemoi** [comment]
The `wwwroot` directory was only registered only for Polyjuice edition.

**Comment by warpech** [comment]
What is the status of this?

**Comment by alemoi** [comment]
Since the big changes that remove Polyjuice are pushed now, probably this issue is no longer relevant. Please close if so.

**Comment by warpech** [comment]
Thanks! Closing
